github: conceptualspace
#patreon: # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#liberapay: # Replace with a single Liberapay username
#otechie: # Replace with a single Otechie username
